### ISSUE TITLE
无法对不标准外观的二维码解析

### ISSUE THREAD

**Issue by Tki-sor** [xh321/LiteLoaderQQNT-QR-Decode#1]
我试了下扫描qq生成的添加好友二维码，大概是这种样子的二维码，虽然涂掉很多但应该能看出来大概什么样子的，jpg格式的。是解析不出来的。而标准外观的二维码是能扫出来的
![image](https://github.com/xh321/LiteLoaderQQNT-QR-Decode/assets/78548154/cb4c0f58-a33f-4753-81f7-18ae64c46c9f)
https://www.zhihu.com/question/19921034 当然，像是这种二维码也是解析不出来的

**Comment by xiaotian2333** [comment]
这是二维码识别库的问题，调用云端api或者更换识别库应该能解决

~使用腾讯自家的识别模型似乎是个不错的选择~ [github 仓库](https://github.com/WeChatCV/opencv_3rdparty)

**Comment by xh321** [comment]
我总觉得一个二维码识别拖个模型是不是有点笨（x
并且用nodejs调腾讯这个opencv过于麻烦了，没有example，我也不会opencv。
如果用在线API的话，嗯，API跑路或者调用限制又是个问题
我试试换一个解析库

**Comment by xh321** [comment]
已经更新了一个版本，可以试试看，换用zxing的库了

**Comment by Tki-sor** [comment]
> 已经更新了一个版本，可以试试看，换用zxing的库了

试了下还是扫不出来，报错是
Error: Uncaught e

**Comment by xh321** [comment]
> > 已经更新了一个版本，可以试试看，换用zxing的库了
> 
> 试了下还是扫不出来，报错是 Error: Uncaught e

那就是无法识别这类二维码了，有可能是因为定位点是圆形的，可能得想办法调用微信的二维码扫描了

**Comment by xh321** [comment]
整个微信二维码模型库有1.42G，而且识别这种比较花里胡哨的二维码还是不行，我看看还是换成API吧

**Comment by xiaotian2333** [comment]
> 整个微信二维码模型库有1.42G，而且识别这种比较花里胡哨的二维码还是不行，我看看还是换成API吧

如果会抓包的话可以试试抓[草料二维码](https://cli.im/deqr/url)的在线解码，传入图片的url就可以了

**Comment by xh321** [comment]
> > 整个微信二维码模型库有1.42G，而且识别这种比较花里胡哨的二维码还是不行，我看看还是换成API吧
> 
> 如果会抓包的话可以试试抓[草料二维码](https://cli.im/deqr/url)的在线解码，传入图片的url就可以了

你跟我想一块去了，最新版已经使用草料API了

**Comment by xh321** [comment]
> > 整个微信二维码模型库有1.42G，而且识别这种比较花里胡哨的二维码还是不行，我看看还是换成API吧
> 
> 如果会抓包的话可以试试抓[草料二维码](https://cli.im/deqr/url)的在线解码，传入图片的url就可以了

不能传入图片URL，因为渲染层拿到的只是本地文件路径

**Comment by xh321** [comment]
目前已经更换为使用草料API，各位可以试试

**Comment by xiaotian2333** [comment]
> > > 整个微信二维码模型库有1.42G，而且识别这种比较花里胡哨的二维码还是不行，我看看还是换成API吧
> > 
> > 
> > 如果会抓包的话可以试试抓[草料二维码](https://cli.im/deqr/url)的在线解码，传入图片的url就可以了
> 
> 不能传入图片URL，因为渲染层拿到的只是本地文件路径

如果能拿到文件图片文件名的话，图片文件名英文转成大写，然后拼接url

``` url
 https://gchat.qpic.cn/gchatpic_new/0/0-0-图片的文件名转大写/0
```

例如，图片的文件名是`07befd18877d76a90fb32f3d8b58decc.jpg`

去掉后缀名是`07befd18877d76a90fb32f3d8b58decc`

转成大写`07BEFD18877D76A90FB32F3D8B58DECC`

拼接成链接`https://gchat.qpic.cn/gchatpic_new/0/0-0-07BEFD18877D76A90FB32F3D8B58DECC/0`

（其实文件名就是图片的MD5，算出来也是可以的）

**Comment by Tki-sor** [comment]
> 目前已经更换为使用草料API，各位可以试试

试了下是能扫出来qq的了，以及特别花里胡哨的（上面发的知乎链接里的）能识别出相当一部分。当然，还是有扫不出来的，例如...
<img width="384" alt="aefa57e3be9f542f85f5e2c362b0abbe" src="https://github.com/xh321/LiteLoaderQQNT-QR-Decode/assets/78548154/24afa68b-0cb1-43d2-9526-1625763a744c">
![image](https://github.com/xh321/LiteLoaderQQNT-QR-Decode/assets/78548154/fa972de9-ee27-422d-aa1b-b52d397cda88)
当然用qq试过了是能扫 <del>（但我大概不会扫这种的吧）</del>

**Comment by xh321** [comment]
> > 目前已经更换为使用草料API，各位可以试试
> 
> 试了下是能扫出来qq的了，以及特别花里胡哨的（上面发的知乎链接里的）能识别出相当一部分。当然，还是有扫不出来的，例如... <img alt="aefa57e3be9f542f85f5e2c362b0abbe" width="384" src="https://user-images.githubusercontent.com/78548154/255867222-24afa68b-0cb1-43d2-9526-1625763a744c.png"> ![image](https://user-images.githubusercontent.com/78548154/255867492-fa972de9-ee27-422d-aa1b-b52d397cda88.png) 当然用qq试过了是能扫 ~（但我大概不会扫这种的吧）~

大部分ok就行了，毕竟草料API我好像没看到有什么限制（
特别花里胡哨的，实在无能为力（

**Comment by xh321** [comment]
> > > > 整个微信二维码模型库有1.42G，而且识别这种比较花里胡哨的二维码还是不行，我看看还是换成API吧
> > > 
> > > 
> > > 如果会抓包的话可以试试抓[草料二维码](https://cli.im/deqr/url)的在线解码，传入图片的url就可以了
> > 
> > 
> > 不能传入图片URL，因为渲染层拿到的只是本地文件路径
> 
> 如果能拿到文件图片文件名的话，图片文件名英文转成大写，然后拼接url
> 
> ```ini
>  https://gchat.qpic.cn/gchatpic_new/0/0-0-图片的文件名转大写/0
> ```
> 
> 例如，图片的文件名是`07befd18877d76a90fb32f3d8b58decc.jpg`
> 
> 去掉后缀名是`07befd18877d76a90fb32f3d8b58decc`
> 
> 转成大写`07BEFD18877D76A90FB32F3D8B58DECC`
> 
> 拼接成链接`https://gchat.qpic.cn/gchatpic_new/0/0-0-07BEFD18877D76A90FB32F3D8B58DECC/0`
> 
> （其实文件名就是图片的MD5，算出来也是可以的）

这样确实更好，我改一下

**Comment by xh321** [comment]
> 

但是草料那个用链接解码的已经不能用了，估计功能下线了

**Comment by xiaotian2333** [comment]
> > 
> 
> 但是草料那个用链接解码的已经不能用了，估计功能下线了

 真是神奇了，我昨天才用过来着，现在是一直显示正在解码
