### ISSUE TITLE
无法直接右键解析二维码

### ISSUE THREAD

**Issue by huyeovo** [xh321/LiteLoaderQQNT-QR-Decode#11]
<img width="611" alt="image" src="https://github.com/user-attachments/assets/4f93d66c-8e9d-4745-a1c6-45a145e29a34">
无法直接右键解析二维码

**Comment by WJZ-P** [comment]
我已经修复了，下载最新版的即可

**Comment by youlan2333** [comment]
> 我已经修复了，下载最新版的即可

貌似还是不行，在聊天窗口右键图片有选项但是点击无反应，只能打开图片查看器窗口右键识别
![image](https://github.com/user-attachments/assets/1d18da22-0455-4090-8fc1-e9414c7cb8a6)
![image](https://github.com/user-attachments/assets/9bd851f3-513c-430d-a977-484a9a4b46e2)

**Comment by WJZ-P** [comment]
在我的电脑上右键之后是有用的，不清楚你为什么不行，可能不兼容新版本的QQ吗，我QQ是26909的

**Comment by huyeovo** [comment]
6.9.56-28418 macOS

**Comment by huyeovo** [comment]
右键没有解析按钮 只有点击放大图片后 右键才有解析按钮

**Comment by youlan2333** [comment]
> 右键没有解析按钮 只有点击放大图片后 右键才有解析按钮

好的

**Comment by huyeovo** [comment]
是什么问题呢

**Comment by WJZ-P** [comment]
> 是什么问题呢

我是对Windows进行了适配，macOS因为我没有这个操作系统的机器，没办法适配。但是直接右键解析没反应我也不知道为啥

**Comment by YsLtr** [comment]
我不打开图片直接右键有解析按钮，但是点了没有任何反应。QQ是Windows版9.9.15-28498 (64位)

**Comment by xh321** [comment]
已知问题，有空我修修

**Comment by xh321** [comment]
已修复，请检查

**Comment by YsLtr** [comment]
> 我不打开图片直接右键有解析按钮，但是点了没有任何反应。QQ是Windows版9.9.15-28498 (64位)

该问题检查后已修复
