### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by shibuyameltdown** [xh321/LiteLoaderQQNT-QR-Decode#3]
qqnt版本 9.9.7-20811 
liteloader版本1.0.1
本插件版本1.33（应该），下载zip解压到plugins目录的
打开设置界面显示是灰色
![QQ截图20240123135354](https://github.com/xh321/LiteLoaderQQNT-QR-Decode/assets/78797438/c573c682-f701-4a18-999c-02aac9e78b4c)

**Comment by shibuyameltdown** [comment]
双击也未见菜单
![image](https://github.com/xh321/LiteLoaderQQNT-QR-Decode/assets/78797438/c6dce8d6-2395-4353-88ea-47b8177327fb)

**Comment by xh321** [comment]
应该是新版本QQ改了窗体路径，我这就做兼容

**Comment by xh321** [comment]
最新版已兼容，同时支持在聊天界面直接右键解码，不需要再双击图片打开预览再解码了

**Comment by shibuyameltdown** [comment]
好快的修
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月24日 16:28 |
| 收件人 | xh321/LiteLoaderQQNT-QR-Decode ***@***.***> |
| 抄送人 | shibuyameltdown ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [xh321/LiteLoaderQQNT-QR-Decode] 无法使用 (Issue #3) |

最新版已兼容，同时支持在聊天界面直接右键解码，不需要再双击图片打开预览再解码了
