### ISSUE TITLE
安装后会影响管理器本身的功能

### ISSUE THREAD

**Issue by RingingVolcano** [xh321/LiteLoaderQQNT-QR-Decode#4]
安装后无法在LiteLoaderQQNT的插件列表中找到这个插件，也就无法单独针对这个插件进行禁用
同时管理器设置页的“目录位置”和最底端的一言会失效
![d199aa9c4bcb60626407f922757822a6](https://github.com/xh321/LiteLoaderQQNT-QR-Decode/assets/72140353/73cd9c48-0934-4c0c-a2cb-c7066e001950)
![a84484a39b1b5dc9f44d3a20b2010cf2](https://github.com/xh321/LiteLoaderQQNT-QR-Decode/assets/72140353/c0bd4c99-6930-4179-b021-03629aa8ee43)
![7047d558bc14b20ebf7dbf0ed013eb5b](https://github.com/xh321/LiteLoaderQQNT-QR-Decode/assets/72140353/25113e8b-48a8-4640-9df2-fe4be295045a)

**Comment by xh321** [comment]
最新版已修复
