### ISSUE TITLE
QQ图片查看器加入此功能

### ISSUE THREAD

**Issue by xingchen-Forever** [xh321/LiteLoaderQQNT-QR-Decode#5]
如题，希望QQ图片查看器下方工具条增加识别二维码图标
![image](https://github.com/xh321/LiteLoaderQQNT-QR-Decode/assets/76945134/ace47560-1aab-4d8e-9e4b-8e8ded4c2639)
希望在图片右键菜单加入识别二维码选项
![image](https://github.com/xh321/LiteLoaderQQNT-QR-Decode/assets/76945134/3777dd90-56f7-410b-8a1a-feec81f97682)

**Comment by xh321** [comment]
这个是QQ更新后才没有的，可能是做了什么调整，等我看看怎么弄

**Comment by xh321** [comment]
最新版已支持
