### ISSUE TITLE
右键菜单中出现了两个重复的“作为二维码解析”

### ISSUE THREAD

**Issue by RingingVolcano** [xh321/LiteLoaderQQNT-QR-Decode#7]
疑似与“轻量工具箱”右键菜单的本地表情功能发生了兼容性问题冲突
![image](https://github.com/xh321/LiteLoaderQQNT-QR-Decode/assets/72140353/9cc65068-7102-47dd-8bf8-a9b646b9b683)
![image](https://github.com/xh321/LiteLoaderQQNT-QR-Decode/assets/72140353/4c6253be-e890-490c-a837-ac90a66fe3d2)

**Comment by xh321** [comment]
最新版已经修复
