### ISSUE TITLE
建议功能

### ISSUE THREAD

**Issue by Starrain08** [xh321/LiteLoaderQQNT-QR-Decode#8]
建议加一个自定义浏览器打开链接，而不是只能默认浏览器

**Comment by Starrain08** [comment]
图片解析出的链接只能默认浏览器打开不太安全

**Comment by xh321** [comment]
此功能已有，只是需要自己修改配置文件，README有写，配置界面还没做

**Comment by xh321** [comment]
OK，会加的

**Comment by xh321** [comment]
最新版已支持，只是需要你手动填写配置文件，详见README

**Comment by Starrain08** [comment]
> 最新版已支持，只是需要你手动填写配置文件，详见README

似乎出现了一点bug，当我按照你给出的文档设置了自定义浏览器，链接能正常识别，但是选择打开后没有任何反应，浏览器位置设置正常，浏览器本身没有问题

**Comment by xh321** [comment]
出了一点小问题，最新版已修复
