### ISSUE TITLE
无法将从移动客户端上发送的图片中识别二维码

### ISSUE THREAD

**Issue by Cyanide-zh** [xh321/LiteLoaderQQNT-QR-Decode#9]
从QQ移动客户端发送私聊给好友或好友从QQ移动客户端发送给我的图片,无法识别其中的二维码。
应该是QQ更改了图片网址构成的方式,如https://github.com/cinit/QAuxiliary/commit/5f000303b2b8158a35d1528215694c1d1e6f5d21
采用这种方式可以获得新的图片网址。
QQ版本:9.9.9-22741 AMD64
LiteLoader版本:1.1.1

**Comment by xh321** [comment]
ok收到，之后有空兼容一下

**Comment by WJZ-P** [comment]
我已经修复了，请下载最新版release即可

**Comment by xh321** [comment]
如暂时无问题先close了
